rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
branches:
  only:
    - master
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails40.gemfile
